### PR TITLE
JDK-8297587: Upgrade JLine to 3.22.0

### PR DESCRIPTION
**Pull request by prkoppul**
Clean backport

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issues
 * [JDK-8297587](https://bugs.openjdk.org/browse/JDK-8297587): Upgrade JLine to 3.22.0 ⚠️ Issue is already resolved. Consider making this a "backport pull request" by setting the PR title to `Backport <hash>` with the hash of the original commit. See [Backports](https://wiki.openjdk.org/display/SKARA/Backports).
 * [JDK-8304498](https://bugs.openjdk.org/browse/JDK-8304498): JShell does not switch to raw mode when there is no /bin/test ⚠️ Issue is already resolved. Consider making this a "backport pull request" by setting the PR title to `Backport <hash>` with the hash of the original commit. See [Backports](https://wiki.openjdk.org/display/SKARA/Backports).

### Reviewers
 * [Sean Coffey](https://openjdk.org/census#coffeys) (@coffeys - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk20u.git pull/56/head:pull/56` \
`$ git checkout pull/56`

Update a local copy of the PR: \
`$ git checkout pull/56` \
`$ git pull https://git.openjdk.org/jdk20u.git pull/56/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 56`

View PR using the GUI difftool: \
`$ git pr show -t 56`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk20u/pull/56.diff">https://git.openjdk.org/jdk20u/pull/56.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk20u/pull/56#issuecomment-1515777174)

### CODE REVIEW

**Comment by prkoppul** [comment]
Reviewers: @coffeys

**Review by coffeys — APPROVED** [review]
Fine with this given that these are clean ports. Don't forget to obtain OpenJDK approval before integration.

**Pull request closed without merging**
