### PR TITLE
8313765: Invalid CEN header (invalid zip64 extra data field size)

### PR DESCRIPTION
**Pull request by benty-amzn**
Backport is not clean, required changes:
- Some context lines
- Changes to `CorruptedZipFiles.java` had to be altered because [8304014](https://bugs.openjdk.org/browse/JDK-8304014) has not been backported to jdk20

All tests in `test/jdk/java/util/zip` pass

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8313765](https://bugs.openjdk.org/browse/JDK-8313765): Invalid CEN header (invalid zip64 extra data field size) (**Bug** - P2)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk20u.git pull/87/head:pull/87` \
`$ git checkout pull/87`

Update a local copy of the PR: \
`$ git checkout pull/87` \
`$ git pull https://git.openjdk.org/jdk20u.git pull/87/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 87`

View PR using the GUI difftool: \
`$ git pr show -t 87`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk20u/pull/87.diff">https://git.openjdk.org/jdk20u/pull/87.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk20u/pull/87#issuecomment-1681514879)

### CODE REVIEW

**Comment by benty-amzn** [comment]
Failing linux GHA looks like infra issues - https://github.com/benty-amzn/jdk20u/actions/runs/5885853677/job/15962891969#step:7:179

**Comment by benty-amzn** [comment]
Windows failures also look like infra issues - https://github.com/benty-amzn/jdk20u/actions/runs/5885853677/job/15962892691#step:5:853

**Comment by gnu-andrew** [comment]
I don't believe there will be any more JDK20 releases, so this probably needs to target openjdk/jdk21u.

**Comment by mrserb** [comment]
But this is still the source code for jdk20u, and we can have a commits here even if the openjdk20u will not release the bundles, other vendors can do that.

**Pull request closed without merging**
